- RetsTalk/RetsTalk/App/AppDelegate.swift
- RetsTalk/RetsTalk/Assets.xcassets/BackgroundMain.colorset/Contents.json
- RetsTalk/RetsTalk/Assets.xcassets/BackgroundRetrospect.colorset/Contents.json
- RetsTalk/RetsTalk/Assets.xcassets/BlazingOrange.colorset/Contents.json
- RetsTalk/RetsTalk/Assets.xcassets/BlueBerry.colorset/Contents.json
- RetsTalk/RetsTalk/Assets.xcassets/StrokeRetrospect.colorset/Contents.json
- RetsTalk/RetsTalk/Info.plist
Closes #41 
Hex 값을 직접 사용하던 기존 코드 대신 사용하기 위한 color asset들을 추가함
10m
> Assets에 Color asset 추가

- RetsTalk/RetsTalk/Chat/Model/MessageManager.swift
- RetsTalk/RetsTalk/Chat/Model/MessageManagerListener.swift
- RetsTalk/RetsTalk/Retrospect/Model/Retrospect.swift
- RetsTalk/RetsTalk/Retrospect/Model/RetrospectManageable.swift
- RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
- RetsTalk/RetsTalk/User/Controller/UserViewController.swift
- RetsTalk/RetsTalk/User/Model/User.swift
- closed: #53 
테스트를 위해서 Model Entity 구현
- 회고 부분에 Create 임시 구현
- 나머지 관리자 부분의 세부 구현은 다른 PR에서 예정입니다.
- 상태 변경을 하는 Method 구현
- 회고 종료를 하는 Method 구현
현재 두개의 함수로 분리를 해줬는데 필요할까 생각해봐야겠네요
```swift
func didFinishRetrospect(_ messageManager: MessageManager) {
guard let index = retrospects
.firstIndex(where: { $0.id == messageManager.retrospectID })
else { return }
retrospects[index].status = .finish
}
func didChangStatus(_ messageManager: MessageManager, to status: Retrospect.Status) {
guard let index = retrospects
.firstIndex(where: { $0.id == messageManager.retrospectID })
else { return }
retrospects[index].status = status
}
```
2h
> 회고와,메시지 관리자 구현체 기본 구성하고 Delegate로 이어주기

- RetsTalk/RetsTalk.xcodeproj/project.pbxproj
- RetsTalk/RetsTalk/Chat/Model/Message.swift
- RetsTalk/RetsTalk/Chat/Model/MessageManageable.swift
- RetsTalk/RetsTalk/Chat/Model/MessageManager.swift
- RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
- RetsTalk/RetsTalk/User/Controller/UserViewController.swift
- RetsTalk/RetsTalkTests/MessageManagerTests.swift
- RetsTalk/RetsTalkTests/MockMessageStore.swift
- RetsTalk/RetsTalkTests/MockRetrospectManager.swift
- closed: #65 
매니저에서 Persistent에서 메시지를 가져오는 함수 구현
- 10개보다 적은 데이터가 있으면 최대까지 들고오는지?
- 2개를 받고 추가로 2개로 받는지
- 날짜순으로 정렬해서 들고오는지
- 최신 날짜의 데이터만 들고오는지
위와 같이 있는 예외들을 테스트로 잡았습니다.
시간순 정렬에서 CoreData에 가면 sortDescriptors로 자동으로 하지만
Mock으로 만든 Persistent에서는 일반적인 배열을 사용해서 
sortDescriptors를 이용해 정렬을 해주기 위해서 함수로 구현해뒀습니다.
아래와 같이 구현을 했었는데
문제점: sortDescriptors를 테스트하는 것 같더라구요.,.
<details><summary>Details</summary>
<p>
```swift
func sortMessages(_ sortDescriptors: [NSSortDescriptor]) -> [Message] {
messages.sorted { lhs, rhs in
for descriptor in sortDescriptors {
let key = descriptor.key
let ascending = descriptor.ascending
let comparisonResult = lhs.createdAt.compare(rhs.createdAt)
return ascending
? comparisonResult == .orderedAscending
: comparisonResult == .orderedDescending
}
return false
}
}
```
</p> …
> MessageManageable의 구체타입 구현(Fetch 부분)

- RetsTalk/RetsTalk.xcodeproj/project.pbxproj
- RetsTalk/RetsTalk/Chat/Model/AssistantMessageProvider.swift
- RetsTalk/RetsTalk/Retrospect/Controller/RetrospectViewController.swift
- RetsTalk/RetsTalk/Retrospect/View/Cell/RetrospectCell.swift
- RetsTalk/RetsTalk/Retrospect/View/RetrospectView.swift
- RetsTalk/RetsTalk/Utility/Enums/Constants.swift
- RetsTalk/RetsTalk/Utility/Extensions/Date+Extension.swift
- RetsTalk/RetsTalk/Utility/Extensions/String+Extension.swift
- closed: #68 
- closed: #73 
회고목록 화면을 구성하는 셀과 테이블뷰에 대한 UI를 구현했습니다.
| iPhone 16 Pro | iPhone SE (3rd generation) |
|---|---|
|<img src="https://github.com/user-attachments/assets/160d35df-db66-4869-a698-df953fcb0f9d" width="250"/>|<img src="https://github.com/user-attachments/assets/b83ceab3-d75b-4197-983a-e9cfa7231422" width="250"/>|
2H
> 회고 목록 화면: 셀, 테이블뷰 UI 구현

- RetsTalk/RetsTalk/Chat/Controller/ChattingViewController.swift
- RetsTalk/RetsTalk/Chat/View/ChatView.swift
- RetsTalk/RetsTalk/Chat/View/MessageInputView.swift
- RetsTalk/RetsTalk/Chat/View/RetryView.swift
- Closes #94 
- Closes #95 
- Closes #96 
|TextInput길이 초기화|재전송 버튼 띄우기|
|-|-|
|<img src="https://i.imgur.com/wjwMSHD.gif" width="350" />|<img src="https://i.imgur.com/Ll2vJJ5.gif" width="350" />|
- 여러 줄의 메시지를 전송한 뒤 InputView의 길이가 줄어들지 않는 문제를 수정하였습니다.
- 올바른 응답이 오지 않아 Retrospect의 state가 responseErrorOccurred인 경우 재전송 버튼(화면)을 띄우게 하는 기능을 추가하였습니다.
- ScrollToTop 메서드를 구현하여 Retrospect의 state가 finished인 경우 해당 함수를 호출하여 맨 위부터 볼 수 있도록 하였습니다.
chatView의 showRetryView(_ completion: ) 함수를 통해 retryView가 추가가 됩니다. 재전송 버튼의 액션이 retryView.addAction() 함수를 통해 closure로 추가할 수 있도록 설계되어 있어서 showRetryView의 completion handler로 부터 재전송 로직이 RetryView까지 전달이 되게 됩니다. (클로저 두 번 중첩됨, ChattingViewController -> ChatView -> RetryView)
이 방식으로 작동이 문제가 없을 지 의문이 들긴 합니다.
Delegate도 그렇고 중첩되거나 여러 번 전달되는 경우 유쾌하지 않은 기분이 듭니다 🤔
5H
> MessageView height 버그 수정, 응답 실패시 재전송 버튼 띄우는 로직 작성, 완료된 회고 맨 위에서 보여주기 기능 추가

- RetsTalk/RetsTalk/User/UserSettingView.swift
- closed: #103 
| swiftUI 뷰 구현 |
|---|
|<img width="250" alt="image" src="https://github.com/user-attachments/assets/c2c8d59b-c46d-4e23-a5c4-9bb91a2cdb14">|
UIKit의 테이블뷰를 이용할 예정이었으나, 셀마다 컴포넌트(액세서리뷰)가 달라 일괄적으로 적용할 수 없고 커스텀셀로 전부 만들기에 소모적이라고 판단하였음.
UIKit로도 서브뷰를 전부 구성하는 것 대신 swiftUI를 활용해 구현해보고자 함.
2시간
> 사용자 설정 화면 UI 구현

- RetsTalk/PersistTests/PersistTests.swift
- RetsTalk/RetsTalk.xcodeproj/project.pbxproj
- RetsTalk/RetsTalk/Chat/Model/RetrospectChatManager.swift
- RetsTalk/RetsTalk/Persistent/Implementation/CoreDataManager.swift
- RetsTalk/RetsTalk/Persistent/Implementation/PersistFetchRequest.swift
- RetsTalk/RetsTalk/Persistent/PersistFetchRequestable.swift
- RetsTalk/RetsTalk/Persistent/Persistable.swift
- RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
- RetsTalk/RetsTalkTests/Mock/MockMessageStore.swift
- RetsTalk/RetsTalkTests/Mock/MockRetrospectStore.swift
- close: #113 
로컬 저장소 레이어를 행위자(actor)를 통해 격리합니다.
- 로컬 저장소 레이어에서 수행하는 작업들이 메인 스레드에서 수행되지 않음을 보장합니다.
- 로컬 저장소 레이어의 데이터 및 로직이 동시성의 상황에서 안전하게 처리됨을 보장합니다.
40m
> 로컬 저장소 레이어 행위자(actor) 격리(#113)

- RetsTalk/RetsTalk/Utility/View/AlertPresentable.swift
- RetsTalk/RetsTalk/Utility/View/BaseKeyBoardViewController.swift
- RetsTalk/RetsTalk/Utility/View/BaseViewController.swift
현재 모든 뷰는 네비게이션 컨트롤러에 속합니다.
- **BaseViewController**
네비게이션 pop 스와이프 제스처와 뒤로가기 액션의 기본구현을 가지며, 뷰컨트롤러 계층화의 기준이 됩니다.
- **BaseKeyboardViewController**
BaseViewController을 서브클래싱하여 키보드 호출과 소멸에 대한 메서드를 기본구현한 뷰컨트롤러입니다.
- **AlertPresentable**
알림을 띄우는 뷰컨트롤러에 대해 프로토콜과 `func presentAlertpresentAlert(for: , actions: )`의 기본구현을 제공합니다.
키보드 호출을 관리하는 기능과 Alert를 띄우는 기능을 둘 다 가져야하는 뷰 컨트롤러에 대해 **다중상속을 받을 수 없으므로**, 키보드 기능과 알림기능에 대해 전부 서브클래싱으로 관리하려면 다음과 같이 세 가지 케이스의 ViewController을 새로 작성해야합니다.
||키보드 기능 O| 키보드 기능 X|
|---|---|---|
|Alert 기능 O|case 1|case 2|
|Alert 기능 X|case 3|BaseViewController|
그러나 이와 같은 구조는 계층화의 의미에서는 벗어난다고 생각하여, 
- 뷰컨트롤러의 생명주기에 관여하는 메소드를 가진 **키보드기능뷰컨트롤러를 계층화**하여 구현하고,
- Alert를 띄우는 기능은 **프로토콜과 기본구현을 제공**하여
문제를 해결했습니다.
1H30M
> 뷰 컨트롤러 계층화

- RetsTalk/RetsTalk/Persistent/Implementation/CoreDataManager.swift
코어데이터매니저의 init 메서드의 오류를 수정했습니다.
> CoreDataManager: init 메서드의 Sendable 핸들러 전달

- RetsTalk/RetsTalk/Chat/Controller/ChattingViewController.swift
- RetsTalk/RetsTalk/Chat/Controller/RetrospectChatViewController.swift
- RetsTalk/RetsTalk/Chat/Model/Message.swift
- RetsTalk/RetsTalk/Chat/Model/RetrospectChatManager.swift
- RetsTalk/RetsTalk/Chat/View/ChatView.swift
- closed: #80 
https://github.com/user-attachments/assets/e5efe76b-18f1-4e7a-9975-227ad9ab41d6
https://github.com/user-attachments/assets/3e5192af-72a3-4247-b63e-2f83c3ace08c 
테이블 뷰를 위로 스크롤 하며, 위에 데이터를 추가할 경우, 테이블 뷰가 이에 대응하는 동안 스크롤 오프셋이 튀는 현상이 발생합니다.
오프셋이 튀면, 불필요한 추가 요청이 발생할 수 있고 그러면 더 심하게 오프셋이 튑니다.
테이블 뷰를 업데이트할 때 오프셋이 변하지 않도록 강제하는 것이 필요한데, 다음의 코드가 이를 만족해줍니다.
```swift
CATransaction.begin()
CATransaction.setDisableActions(true)
chattingTableView.insertRows(at: indexPaths, with: .none)
CATransaction.commit()
```
아직 정확한 이유는 모르지만,
CoreAnimation 수준에서 원자적으로 작업을 수행하고, 애니메이션을 비활성화해서 오프셋이 그대로 유지되도록 처리되는 것으로 보입니다.
추가로 추가 요청은, 테이블 뷰의 컨텐츠 크기와 시간 그리고 드래깅 여부로 판단해서 최대한 불필요한 중복을 제거했습니다.
```swift
static func == (lhs: ScrollInfo, rhs: ScrollInfo) -> Bool {
let isDragging = lhs.isDragging || rhs.isDragging …
```
> 채팅 prepend 기능 추가

- RetsTalk/RetsTalk.xcodeproj/project.pbxproj
- RetsTalk/RetsTalk/App/SceneDelegate.swift
- RetsTalk/RetsTalk/Chat/Model/RetrospectChatManageable.swift
- RetsTalk/RetsTalk/Chat/Model/RetrospectChatManager.swift
- RetsTalk/RetsTalk/Chat/Model/RetrospectChatManagerListener.swift
- RetsTalk/RetsTalk/Retrospect/Controller/RetrospectListViewController.swift
- RetsTalk/RetsTalk/Retrospect/Model/MockRetrospectManager.swift
- RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
- RetsTalk/RetsTalk/Utility/View/BaseViewController.swift
- RetsTalk/RetsTalkTests/Mock/MockRetrospectManager.swift
- RetsTalk/RetsTalkTests/Mock/MockTestRetrospectManager.swift
- RetsTalk/RetsTalkTests/RetrospectChatManagerTests.swift
- Lint 에러나는 부분 수정
- RetrospectChatManager 네이밍에 따른 수정사항 반영
- View에서 임시로 만든 Mock 회고 매니저 부분에서 나는 에러 해결
- Test의 Mock과 View의 Mock 네이밍이 같아서 일어나는 에러 해결
20m
> 빌드 에러나는 부분 수정

- RetsTalk/RetsTalk/User/Model/UserSettingManager.swift
- RetsTalk/RetsTalk/User/Subview/CloudSettingView.swift
- RetsTalk/RetsTalk/User/UserSettingView.swift
- closed: #148 
클라우드 동기화 설정을 켜고 끌 수 있는 기능을 추가했습니다.
실제 클라우드 연동과는 별개로 유저데이터를 저장하는 기능만 수행합니다.
20M
> 클라우드 동기화 on/off 기능

- RetsTalk/RetsTalk/User/Model/UserData.swift
- RetsTalk/RetsTalk/User/Model/UserSettingManageable.swift
- RetsTalk/RetsTalk/User/Model/UserSettingManager.swift
- closed: #151 
- closed: #152 
- closed: #153 
앱 진입 시점에서 사용자 설정 정보의 아이디를 가져오는 작업이 필수적으로 요구됩니다.
UserSettingManageable의 `initialize()` 메서드는 UserDefaults에 저장된 사용자 정보를 가져오고 아이디를 반환합니다.
만약 정보가 없으면, 새로운 사용자 정보를 저장하고 반환합니다.
이 작업은 비동기적으로 이루어지며, 앱 진입 시점에 Task 블록을 통해 비동기작업을 수행합니다.
추가적으로, UserDefaults는 UUID 타입을 저장할 수 없어 문자열로 변환해 저장하도록 했습니다.
앱 진입시점 이외에, UserSettingManager을 통한 userID 접근이 필요할 경우에는 반환타입이 `String`임을 미리 알립니다.
앱 진입 시점에서 사용자 설정 정보를 가져오는 비동기작업이 필수이므로, 해당 작업이 진행되는 동안 (매우 잠시) 화면이 표시되지 않는 모습을 보였습니다. 잠깐 검은 화면을 띄운 후에 회고목록화면이 보이므로, 스플래시 화면이 필요할 것으로 예상됩니다.
2H
> UserSettingManager: 사용자 ID 반환/부여하는 기능

- RetsTalk/RetsTalk.xcodeproj/project.pbxproj
- RetsTalk/RetsTalk/Retrospect/Controller/RetrospectListViewController.swift
- RetsTalk/RetsTalk/Retrospect/Model/SortedRetrospects.swift
- RetsTalk/RetsTalk/Retrospect/View/RetrospectListView.swift
- RetsTalk/RetsTalk/Retrospect/View/SectionHeaderView.swift
- RetsTalk/RetsTalk/Utility/RetrospectSortingHelper.swift
- closed: #179 
- 테이블뷰의 잦은 변화에 대응하여 UITableViewDatasource에 대해 DiffableDatasource로 리팩토링을 진행했습니다.
- 헤더를 적용하기 위한 SectionHeaderView를 추가했습니다.
기존의 데이터소스의 섹션 할당방식과 다르게 DiffableDatasource 스냅샷의 섹션은 존재할 수 있는 섹션 중 활성화된 섹션들만을 반환하였고, 이에 대해 헤더 이름을 매칭하기 위해 Section 열거형 타입의 rawValue를 이용하기로 하였고,
Int, CaseIterable을 채택하게 되었습니다.
3H
> 회고목록 테이블뷰: DiffableDatasource 리팩토링

- RetsTalk/RetsTalk/Chat/Model/AssistantMessageProvider.swift
- RetsTalk/RetsTalk/Chat/Model/RetrospectChatManager.swift
- RetsTalk/RetsTalk/Chat/Model/RetrospectChatManagerListener.swift
- RetsTalk/RetsTalk/Network/CLOVAStudio/CLOVAStudioManager.swift
- RetsTalk/RetsTalk/Network/NetworkRequestable.swift
- RetsTalk/RetsTalk/Persistent/Implementation/CoreDataManager.swift
- RetsTalk/RetsTalk/Persistent/Implementation/UserDefaultsManager.swift
- RetsTalk/RetsTalk/Persistent/Persistable.swift
- RetsTalk/RetsTalk/Retrospect/Controller/RetrospectListViewController.swift
- RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
- RetsTalk/RetsTalk/Retrospect/Model/SummaryProvider.swift
- RetsTalk/RetsTalk/User/Model/UserSettingManager.swift
- closed: #176 
Network 영역에 Network 요청 부분을 아래와 같이 Sendable하게 만들었습니다.
|NetworkRequestable|AssistantMessageProvidable|SummaryProvider|
|---|---|---|
|<img width="481" alt="image" src="https://github.com/user-attachments/assets/af17dae9-7fcb-4093-bffa-8661ed2dbfba">|<img width="678" alt="image" src="https://github.com/user-attachments/assets/9afddc4e-508a-40c6-a75a-02905e52c7bb">|<img width="608" alt="image" src="https://github.com/user-attachments/assets/0d853995-b713-47fc-a739-5aad108947ba">|
위와 같이 Sendable하게 만들고 아래처럼 사용하는 부분에 Actor에 맞게 되도록 했습니다
-> `모든 Actor 타입은 Sendable함!`
<br><br><br>
그렇게 변경됨에 따라 회고 Actor에서 네트워크 요청을 Provider를 통해 비동기적으로 받아오고 있습니다.
<br><br><br>
아래와 같이 인스턴스가 각 구현체에 맞게 격리 되도록 했습니다.
|Retrospect Actor|Main Actor|
|---|---|
|<img width="662" alt="image" …
> Persistent, Network 영역에 격리를 없애고 각 부분에 맞는 격리로 되도록 개선

- RetsTalk/RetsTalk/Retrospect/Controller/RetrospectListViewController.swift
- RetsTalk/RetsTalk/Retrospect/Model/Retrospect.swift
- RetsTalk/RetsTalk/Retrospect/Model/RetrospectManageable.swift
- RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
- closed: #196 
- 마지막회고를 기준으로 이전의 회고를 가져오는 기능
- 스크롤뷰의 contentOffset을 기준으로 이전 회고를 가져와 테이블 업데이트
매니저가 관리하는 회고 배열에는 고정됨/진행중 항목과 같이 시간순과는 관계없는 데이터가 존재합니다.
따라서 과거의 끝난 회고를 불러올 때, 현재 회고 배열의 마지막 요소를 기준으로 과거만 필터링하는 predicate을 이용했습니다.
2H
> 회고목록화면: 스크롤링을 통한 이전 회고 불러오기

- RetsTalk/RetsTalk/Retrospect/Controller/RetrospectListViewController.swift
- RetsTalk/RetsTalk/Retrospect/Model/Retrospect.swift
- closed: #204 
- 마지막 메시지 변경 시 셀을 재렌더링하기 위해,  Retrospect 모델에 hash(into:) 메서드와 Equatable 조건을 추가하여 변경 사항을 감지하도록 구현했습니다.
1H  미만
> 회고목록화면: 진행 중인 회고에 대해 마지막 메세지를 셀에 보여주는 기능

- RetsTalk/RetsTalk/Retrospect/Controller/RetrospectListViewController.swift
- RetsTalk/RetsTalk/Retrospect/Model/Retrospect.swift
- RetsTalk/RetsTalk/Retrospect/Model/RetrospectManageable.swift
- RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
- RetsTalk/RetsTalk/Retrospect/View/RetrospectListView.swift
- closed: #192 
회고한 일수 대신 이달의 회고 개수를 볼 수 있는 버튼으로 수정하였습니다.
fetch요청 시점의 Date를 기준으로 한 달간 작성한 회고를 가져오는 predicate을 이용합니다.
2H 미만
> 회고목록화면: 이달의 회고 수 기능

- RetsTalk/RetsTalk/Chat/Controller/RetrospectChatViewController.swift
- RetsTalk/RetsTalk/Chat/Model/RetrospectChatManager.swift
- RetsTalk/RetsTalk/Chat/View/ChatView.swift
- RetsTalk/RetsTalk/Chat/View/MessageInputView.swift
- RetsTalk/RetsTalk/Chat/View/RetryView.swift
- RetsTalk/RetsTalk/Network/NetworkRequestable.swift
- closed: #93 
https://github.com/user-attachments/assets/a2967390-5af0-42a3-916d-254d5ce83da2
- 좌하단에 요청중 인디케이터가 뜹니다.
- 실패의 경우 재요청을 할 수 있는 화면이 뜹니다.
- 끝이 나지 않은 회고의 경우, 요약이 마지막 메시지로 들어갑니다.
- 레이아웃은 leading과 trailing을 활용하고(아랍대비 ㅎㅎ), 세이프 에어리어를 활용해서 가로스크린에 대응합니다.
2h
> 회고 도움 요청 표시 및 재시도 기능 추가(#93)

- RetsTalk/RetsTalk/Chat/Controller/RetrospectChatViewController.swift
- RetsTalk/RetsTalk/Chat/Model/RetrospectChatManager.swift
- RetsTalk/RetsTalk/Chat/View/ChatView.swift
- RetsTalk/RetsTalk/Chat/View/MessageInputView.swift
- RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
- RetsTalk/RetsTalk/Utility/Extensions/UIImage+Extension.swift
- RetsTalk/RetsTalk/Utility/View/AlertPresentable.swift
- close: #218 
- close: #219 
- close: #220 
https://github.com/user-attachments/assets/464eee16-9f9c-4c5e-bf7f-09d797be23f0
- 회고를 끝낼때 Alert를 통해 한 번 더 물어봅니다.
- 오류가 나면 Alert를 통해 알려줍니다.
- 끝난 회고에서 고정을 토글할 수 있습니다.
- iPhone SE (iOS16.0) 정상 작동 확인.
2h
> 회고 대화 오류/끝내기 Alert 및 고정 기능(#218)

- RetsTalk/.swiftlint.yml
- RetsTalk/RetsTalk/Retrospect/Model/Retrospect.swift
- RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
- RetsTalk/RetsTalk/RetrospectCalendar/Controller/RetrospectCalendarTableViewController.swift
- RetsTalk/RetsTalk/RetrospectCalendar/Controller/RetrospectCalendarViewController.swift
- RetsTalk/RetsTalk/RetrospectCalendar/Model/RetrospectCalendarManageable.swift
- RetsTalk/RetsTalk/RetrospectCalendar/Model/RetrospectCalendarManager.swift
- RetsTalk/RetsTalk/RetrospectCalendar/View/RetrospectCalendarView.swift
- closed: #216 
중복되는 부분이 많아서 추후에 상속으로 변경해야할 것 같습니다.
- monthly 파라미터 네이밍에 대한 변경
`case monthly(fromDate: Date, toDate: Date)`
- Swift Lint File Length를 500부터 warning 표시하도록 변경
사실 manager를 회고 매니저로 같이 쓰면
1. 회고 캘린더에서 한달을 가져오면
2. 회고 리스트에 돌아갔을때 중첩 에러가 날거라 생각
그래서 리스트와 캘린더 매니저를 분리
하지만 문제점은 두 부분이 완전 똑같음
- 회고 캘린더 매니저
```swift
@RetrospectActor
protocol RetrospectCalendarManageable: Sendable {
var retrospects: [Retrospect] { get }
var retrospectsPublisher: AnyPublisher<[Retrospect], Never> { get }
var errorPublisher: AnyPublisher<Error, Never> { get }
func retrospectChatManager(of retrospect: Retrospect) -> RetrospectChatManageable?
func fetchRetrospects(of kindList: [Retrospect.Kind])
func finishRetrospect(_ retrospect: Retrospect) async
}
```
- 회고 매니저
```swift
@RetrospectActor
protocol …
```
> 회고 매니저와 회고 캘린더 매니저 분리
